### ISSUE TITLE
Pinned: Where to put issues

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu.github.io#3]
Hi, trovu consists of several repos, here's where to put issues:

- [trovu-web/issues](https://github.com/trovu/trovu-web/issues) – trovu-web is the web interface at [trovu.net](https://trovu.net). This is probably the most likely place. 
- [trovu-data/issues](https://github.com/trovu/trovu-data/issues) – trovu-data is the shortcut repository. Raise here any problems with not working shortcuts.
- [trovu.github.io/issues](https://github.com/trovu/trovu.github.io/issues) – trovu.github.io is the documentation repository. Ask about missing documentation – or edit the wiki yourself.

**Comment by texttheater** [comment]
And documentation issues should go into this here repo, I guess? :)

**Comment by georgjaehnig** [comment]
> And documentation issues should go into this here repo, I guess? :)

Yup. :)
Updated the ticket above.
