### ISSUE TITLE
Add "Troubleshooting" page to wiki?

### ISSUE THREAD

**Issue by texttheater** [trovu/trovu.github.io#4]
Here's a first snippet of documentation that could go on the troubleshooting page:

**I Edited a Shortcut, but It Has No Effect**

This might be a caching issue.

First of all, make sure that GitHub has updated the raw version of the shortcut file you edited. Click on the “raw” button and keep refreshing the page until you see your changes.

Second, clear your browser cache. There are extensions that make this easy, such as [Clear Cache](https://addons.mozilla.org/de/firefox/addon/clearcache/) for Firefox or [Clear Cache](https://chrome.google.com/webstore/detail/clear-cache/cppjkneekbjaeellbfkmgnhonkkjfpdn) for Chrome.

**Comment by georgjaehnig** [comment]
Great idea, added it here: https://github.com/trovu/trovu.github.io/wiki/Troubleshooting

Wasn't the wiki editable for you?

**Comment by texttheater** [comment]
Nope :/

**Comment by georgjaehnig** [comment]
Ah, I found the setting. Should work now.

**Comment by texttheater** [comment]
Confirmed - thanks! :)
